In [ ]:
Q1. What are the benefits of the built-in array package, if any?

In [ ]:
Advantages of Arrays
1.Arrays are similar to lists. ...
2.The size of the array is not fixed in Python. ...
3.Arrays can grow or shrink in memory dynamically (during runtime).
4.Arrays are useful to handle a collection of elements like a group of numbers or characters.

In [ ]:
Q2. What are some of the array package's limitations?

In [ ]:
1.An array which is formed will be homogeneous. ...
2.While declaring an array, passing size of an array is compulsory, and the size must be a constant. ...
Shifting is required for insertion or deletion of elements in an array.

In [ ]:
Q3. Describe the main differences between the array and numpy packages.

In [ ]:
An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a
mechanism of specifying the data types.

In [ ]:
Q4. Explain the distinctions between the empty, ones, and zeros functions.

In [ ]:
empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, 
it requires the user to manually set all the values in the array, and should be used with caution. Return a new array 
setting values to zero.

In [ ]:
Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

In [ ]:
In the 'numpy.fromfunction' function ,the 'callable' argument is used to specify a function that will be called for every
element in the output array.The function should take as arguments a set of indices that correspond to the position of each 
element in the array, and return a value that will be placed at that position.
The 'callable' argument can be any Python callable object ,such as a function ,a lambda ,or even a class with a '__call__'
method.It can also take additional arguments ,which can be passed to the callable using the 'args' argument of the 'args'
argument of the 'fromfunction' function.The 'callable' argument provides a powerful way to generate new arrays with custom 
values based on a specified function of the array indices.

In [ ]:
Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point
value) through addition, as in the expression A + n?

In [ ]:
In Python, when a NumPy array is combined with a single value operand through addition, as in the expression 'A+n', where
'A' is a NumPy array and 'n' is a scalar (e.g. an int or a floating-point value), NumPy applies the addition operation 
element-wise between the array and the scalar value.


In [2]:
import numpy as np
A=np.array([[1,2],[2,5],[4,6]])
n=4
A_plus_n=A+n
print(A_plus_n)

[[ 5  6]
 [ 6  9]
 [ 8 10]]


In [ ]:
Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

In [ ]:
Yes, NumPy allows array-to-scalar operations to use combined operation-assign operations,such as '+=' or '*='.These 
operators modify the original array in place by applying the corresponding operation to each element of the array and the 
scalar value.

In [6]:
import numpy as np
A=np.array([1,2,5,6,3])
A+=2
print(A)

[3 4 7 8 5]


In [7]:
import numpy as np
A=np.array([1,2,5,6,3])
A*=2
print(A)

[ 2  4 10 12  6]


In [ ]:
Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

In [ ]:
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an 
ndarray will create a new array and delete the original. The elements in a NumPy array are all required to be of the same 
data type, and thus will be the same size in memory.
Buffer overflow occurs when data is input or written beyond the allocated bounds of a buffer, array, or other object 
causing a program crash or a vulnerability that hackers might exploit.

In [ ]:
Q9. What happens when you combine two numpy arrays using an operation like addition (+) or
multiplication (*)? What are the conditions for combining two numpy arrays?

In [ ]:
Add is a new Numpy array that contains the element-wise sum of the values of the input arrays. Also note that the output 
is slightly different for scalars: If the both inputs to np. add are scalar values, then the output will be a scalar.

You can use np. multiply to multiply two same-sized arrays together. This computes something called the Hadamard product. 
In the Hadamard product, the two inputs have the same shape, and the output contains the element-wise product of each of 
the input values.

In [ ]:
Q10. What is the best way to use a Boolean array to mask another array?

In [ ]:
To create a boolean mask from an array, use the ma. make_mask() method in Python Numpy. The function can accept any 
sequence that is convertible to integers, or nomask. Does not require that contents must be 0s and 1s, values of 0 are 
interpreted as False, everything else as True.

In [ ]:
Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python 
and its packages? Sort the three of them by how quickly they execute.

In [ ]:
There are several ways to get the standard deviation of a data set in Python both using standard Python and its packages 
Here are three different ways ,sorted by execution speed:
1.NumPy packges-'numpy.std()' function: NumPy is a popular numerical computing library for Python that provides many useful
functions for data analysis.
2.Pandas package-'Pandas.DataFrame.std()' method:Pandas is another popular library for data manipulation and analysis in 
Python.It provides a convenient 'DataFrame' class that allows you to workwith tabular data.
3.Standard Python:'statistics.stdev()' function:If you don't want to use any external libraries ,you can use the built-in 
'statistics' module of Python to calculate the standard deviation of a data set.

In [ ]:
12. What is the dimensionality of a Boolean mask-generated array?

In [ ]:
What is returned is a one-dimensional array filled with all the values that meet this condition; in other words, all the
values in positions at which the mask array is True .